// src/app/game/components/circularTimer/CircularTimer.tsx
import React from "react";

export default function CircularTimer({
    x,
    xMax,
}: {
    x: number;
    xMax: number;
}) {
    return (
        <div
            style={{
                color: "var(--main-light-color)",
                display: "grid",
                placeItems: "center",
                borderRadius: "50%",
                fontSize: "20px",
                width: "50px",
                height: "50px",
                border: "7px solid transparent",
                alignSelf: "start",
                justifySelf: "end",
                background: `linear-gradient(var(--main-dark-color), var(--main-dark-color)) content-box no-repeat,
                    conic-gradient(transparent ${Math.floor(
                        ((xMax - x) / xMax) * 100
                    )}%, 0,var(--main-light-color)) border-box`,
            }}
        >
            {x}
        </div>
    );
}

// src/components/round/CircularTimer.vue
<script setup lang="ts">
defineProps<{
  x: number
  xMax: number
}>()
</script>

<template>
  <div
    :style="`--percentage: ${Math.floor(
      ((xMax - x) / xMax) * 100,
    )}%`"
    class="circle-background grid size-12 place-items-center rounded-full border-8 border-transparent text-xl text-primary"
  >
    {{ x }}
  </div>
</template>

<style scoped>
.circle-background {
  background:
    var(--gradient-background) fixed content-box no-repeat,
    conic-gradient(transparent var(--percentage), 0, hsl(var(--primary)))
      border-box;
}
</style>
